name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry + build
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build all crates (libs + tests only)
        run: cargo build --workspace --lib --tests --locked

      - name: Run tests for all crates
        run: cargo test --workspace --all-features --locked
